apiVersion: v1
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-c95jf
  creationTimestamp: "2020-12-18T01:53:05Z"
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:POSTGRES_PASSWORD: {}
        f:POSTGRES_USER: {}
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-12-18T01:53:05Z"
  name: postgres-db
  namespace: servian
  resourceVersion: "40232101"
  selfLink: /api/v1/namespaces/servian/secrets/postgres-db
  uid: 4be62469-f371-4e71-b6f9-d92b75ec6b4a
type: Opaque
